-- Seed RBAC: vai trò hệ thống và quyền mặc định (idempotent).
INSERT OR IGNORE INTO roles (id, key, name_vi, is_system) VALUES ('role_super_admin', 'super_admin', 'Quản trị viên cấp cao', 1);
INSERT OR IGNORE INTO roles (id, key, name_vi, is_system) VALUES ('role_admin', 'admin', 'Quản trị viên', 1);
INSERT OR IGNORE INTO roles (id, key, name_vi, is_system) VALUES ('role_moderator', 'moderator', 'Kiểm duyệt viên', 1);
INSERT OR IGNORE INTO roles (id, key, name_vi, is_system) VALUES ('role_teacher', 'teacher', 'Giáo viên', 1);
INSERT OR IGNORE INTO roles (id, key, name_vi, is_system) VALUES ('role_student', 'student', 'Học sinh', 1);
INSERT OR IGNORE INTO roles (id, key, name_vi, is_system) VALUES ('role_parent', 'parent', 'Phụ huynh', 1);
INSERT OR IGNORE INTO roles (id, key, name_vi, is_system) VALUES ('role_support_agent', 'support_agent', 'Nhân viên hỗ trợ', 1);
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_users_view', 'users:view', 'Xem người dùng');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_users_manage', 'users:manage', 'Quản lý người dùng');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_roles_manage', 'roles:manage', 'Quản lý vai trò và quyền');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_grades_view', 'grades:view', 'Xem lớp học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_grades_manage', 'grades:manage', 'Quản lý lớp học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_subjects_view', 'subjects:view', 'Xem môn học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_subjects_manage', 'subjects:manage', 'Quản lý môn học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_cms_view', 'cms:view', 'Xem CMS');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_cms_manage', 'cms:manage', 'Quản lý CMS và trang chủ');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_audit_view', 'audit:view', 'Xem nhật ký hệ thống');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_settings_manage', 'settings:manage', 'Quản lý cấu hình hệ thống');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_courses_view', 'courses:view', 'Xem khóa học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_courses_create', 'courses:create', 'Tạo khóa học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_courses_update', 'courses:update', 'Cập nhật khóa học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_courses_delete', 'courses:delete', 'Xóa khóa học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_courses_publish', 'courses:publish', 'Xuất bản khóa học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_courses_approve', 'courses:approve', 'Duyệt khóa học');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_content_moderate', 'content:moderate', 'Kiểm duyệt nội dung');
INSERT OR IGNORE INTO permissions (id, key, description) VALUES ('perm_support_manage', 'support:manage', 'Quản lý hỗ trợ');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_users_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_users_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_users_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_users_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_roles_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_roles_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_grades_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_grades_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_grades_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_grades_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_subjects_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_subjects_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_subjects_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_subjects_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_cms_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_cms_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_cms_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_cms_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_audit_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_audit_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_settings_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_settings_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_courses_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_courses_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_courses_create' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_courses_create');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_courses_update' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_courses_update');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_courses_delete' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_courses_delete');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_courses_publish' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_courses_publish');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_courses_approve' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_courses_approve');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_content_moderate' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_content_moderate');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_super_admin', 'perm_support_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_super_admin' AND permission_id = 'perm_support_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_users_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_users_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_users_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_users_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_grades_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_grades_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_grades_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_grades_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_subjects_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_subjects_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_subjects_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_subjects_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_cms_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_cms_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_cms_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_cms_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_audit_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_audit_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_courses_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_courses_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_courses_create' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_courses_create');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_courses_update' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_courses_update');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_courses_delete' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_courses_delete');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_courses_publish' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_courses_publish');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_courses_approve' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_courses_approve');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_content_moderate' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_content_moderate');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_admin', 'perm_support_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_admin' AND permission_id = 'perm_support_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_moderator', 'perm_courses_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_moderator' AND permission_id = 'perm_courses_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_moderator', 'perm_content_moderate' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_moderator' AND permission_id = 'perm_content_moderate');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_moderator', 'perm_users_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_moderator' AND permission_id = 'perm_users_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_moderator', 'perm_grades_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_moderator' AND permission_id = 'perm_grades_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_moderator', 'perm_subjects_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_moderator' AND permission_id = 'perm_subjects_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_teacher', 'perm_grades_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_teacher' AND permission_id = 'perm_grades_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_teacher', 'perm_subjects_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_teacher' AND permission_id = 'perm_subjects_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_teacher', 'perm_courses_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_teacher' AND permission_id = 'perm_courses_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_teacher', 'perm_courses_create' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_teacher' AND permission_id = 'perm_courses_create');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_teacher', 'perm_courses_update' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_teacher' AND permission_id = 'perm_courses_update');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_teacher', 'perm_courses_delete' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_teacher' AND permission_id = 'perm_courses_delete');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_student', 'perm_grades_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_student' AND permission_id = 'perm_grades_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_student', 'perm_subjects_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_student' AND permission_id = 'perm_subjects_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_student', 'perm_courses_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_student' AND permission_id = 'perm_courses_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_parent', 'perm_grades_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_parent' AND permission_id = 'perm_grades_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_parent', 'perm_subjects_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_parent' AND permission_id = 'perm_subjects_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_parent', 'perm_courses_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_parent' AND permission_id = 'perm_courses_view');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_support_agent', 'perm_support_manage' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_support_agent' AND permission_id = 'perm_support_manage');
INSERT OR IGNORE INTO role_permissions (role_id, permission_id) SELECT 'role_support_agent', 'perm_users_view' WHERE NOT EXISTS (SELECT 1 FROM role_permissions WHERE role_id = 'role_support_agent' AND permission_id = 'perm_users_view');

-- Mặc định: 12 lớp theo cấp học (Tiểu học 1–5, THCS 6–9, THPT 10–12).
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_1', 1, 'lop-1', 'Lớp 1', 'primary', 1);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_2', 2, 'lop-2', 'Lớp 2', 'primary', 2);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_3', 3, 'lop-3', 'Lớp 3', 'primary', 3);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_4', 4, 'lop-4', 'Lớp 4', 'primary', 4);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_5', 5, 'lop-5', 'Lớp 5', 'primary', 5);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_6', 6, 'lop-6', 'Lớp 6', 'lower_secondary', 6);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_7', 7, 'lop-7', 'Lớp 7', 'lower_secondary', 7);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_8', 8, 'lop-8', 'Lớp 8', 'lower_secondary', 8);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_9', 9, 'lop-9', 'Lớp 9', 'lower_secondary', 9);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_10', 10, 'lop-10', 'Lớp 10', 'upper_secondary', 10);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_11', 11, 'lop-11', 'Lớp 11', 'upper_secondary', 11);
INSERT OR IGNORE INTO grades (id, level, slug, name_vi, stage, sort_order) VALUES ('grade_12', 12, 'lop-12', 'Lớp 12', 'upper_secondary', 12);

-- Mặc định: môn học phổ biến (có thể thêm/sửa bởi quản trị viên).
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_toan', 'toan', 'Toán học', 0, 1);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_tieng-viet', 'tieng-viet', 'Tiếng Việt', 0, 2);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_van-hoc', 'van-hoc', 'Ngữ văn', 0, 3);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_tieng-anh', 'tieng-anh', 'Tiếng Anh', 0, 4);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_vat-li', 'vat-li', 'Vật lí', 0, 5);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_hoa-hoc', 'hoa-hoc', 'Hóa học', 0, 6);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_sinh-hoc', 'sinh-hoc', 'Sinh học', 0, 7);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_lich-su', 'lich-su', 'Lịch sử', 0, 8);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_dia-li', 'dia-li', 'Địa lí', 0, 9);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_tin-hoc', 'tin-hoc', 'Tin học', 0, 10);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_cong-nghe', 'cong-nghe', 'Công nghệ', 0, 11);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_gdcd', 'gdcd', 'Giáo dục công dân', 0, 12);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_khtn', 'khtn', 'Khoa học tự nhiên', 0, 13);
INSERT OR IGNORE INTO subjects (id, slug, name_vi, is_custom, sort_order) VALUES ('subject_lich-su-dia-li', 'lich-su-dia-li', 'Lịch sử và Địa lí', 0, 14);

-- Mặc định: cấu trúc trang chủ (CMS). Nội dung là văn bản mẫu, có thể chỉnh sửa.
INSERT OR IGNORE INTO homepage_sections (id, key, type, title_vi, config, position, is_enabled) VALUES ('section_hero', 'hero', 'hero', 'Khám phá TIMO', '{"slides": [{"title": "Học mọi lúc, giỏi mọi nơi.", "subtitle": "Bài giảng, bài tập và đề thi theo Chương trình GDPT 2018 – Kết nối tri thức với cuộc sống.", "ctaLabel": "Bắt đầu học", "ctaHref": "/hoc-bai"}]}', 1, 1);
INSERT OR IGNORE INTO homepage_sections (id, key, type, title_vi, config, position, is_enabled) VALUES ('section_announcement', 'announcement', 'announcement', 'Thông báo', '{"message": "Phiên bản thử nghiệm TIMO – một số tính năng đang được hoàn thiện.", "tone": "info", "enabled": true}', 2, 1);
INSERT OR IGNORE INTO homepage_sections (id, key, type, title_vi, config, position, is_enabled) VALUES ('section_grades', 'grades', 'grades', 'Chọn lớp học', '{"groups": ["primary", "lower_secondary", "upper_secondary"]}', 3, 1);
INSERT OR IGNORE INTO homepage_sections (id, key, type, title_vi, config, position, is_enabled) VALUES ('section_featured_courses', 'featured_courses', 'featured_courses', 'Khóa học nổi bật', '{"limit": 6, "note": "Sẽ hiển thị khi có khóa học được xuất bản."}', 4, 1);
INSERT OR IGNORE INTO homepage_sections (id, key, type, title_vi, config, position, is_enabled) VALUES ('section_subjects', 'subjects', 'subjects', 'Môn học phổ biến', '{"limit": 12}', 5, 1);
INSERT OR IGNORE INTO homepage_sections (id, key, type, title_vi, config, position, is_enabled) VALUES ('section_features', 'features', 'features', 'Lợi ích khi học cùng TIMO', '{"items": [{"title": "Học theo tốc độ của bạn", "description": "Truy cập bài học theo thứ tự bạn chọn."}, {"title": "Luyện tập có phản hồi", "description": "Bài tập trắc nghiệm được chấm tự động, kèm lời giải."}, {"title": "Theo dõi tiến độ", "description": "Xem lại kết quả và điểm mạnh, điểm yếu của bạn."}]}', 6, 1);
INSERT OR IGNORE INTO homepage_sections (id, key, type, title_vi, config, position, is_enabled) VALUES ('section_cta', 'cta', 'cta', 'Sẵn sàng bắt đầu?', '{"ctaLabel": "Đăng nhập", "ctaHref": "/dang-nhap"}', 7, 1);
